### ISSUE TITLE
Merge to master

### ISSUE THREAD

**Issue by glenfe** [boostorg/pool#24]
Reminder to please merge 37b504b3366c69129566bdbdff0e9f62c8457241 to master before the release.

**Comment by jeking3** [comment]
Thanks.  @eldiener and @mjcaisse FYI the boost development calendar is empty for the rest of the year and into next.

**Comment by jeking3** [comment]
@glenfe I see a number of error code 134 regressions in the test results on the test matrix for pool/develop in the test that was altered as compared to pool/master results.  I'm not going to merge to master until this is resolved or explained.

**Comment by mjcaisse** [comment]
I've got this one. I'm also reviewing the threading changes from Peter.

**Comment by mjcaisse** [comment]
merged

**Comment by jeking3** [comment]
All the test suites in the test matrix went from green to yellow as a result of this change.  Sounds like you have a handle on it.

**Comment by glenfe** [comment]
Not as a result of this change. As a result of a change in Boost.Core. Because the pool tests were defective. They will all turn to green - eventually.
