### ISSUE TITLE
MSVC failed compilation when use C++20 standard

### ISSUE THREAD

**Issue by joelpelaez** [boostorg/pool#49]
**Issue description:**
Boost pool library has compilation issues with MSVC compiler on C++20 standard mode when the preprocessor macros _min_ and _max_ are defined. It can happens when some Windows specific headers are included to the project.

Note: the files has already some mechanism to avoid this issues with other instances of _max_ calls.

**Reproduce steps:**

1. Use the next code:
```
#include <windows.h>
#include <boost/pool/pool.hpp>

using namespace std;

int main()
{
    return 0;
}
```
2. Compile it using MSVC compiler with c++20 standard with Boost headers only.

**ErrorMessage:**
Error	C2589	'(': illegal token on right side of '::'	D:\boost\include\boost-1_80\boost\pool\pool.hpp	363

**Header code:**
https://github.com/boostorg/pool/blob/600bcb027379b0670ccecf14f380f77e1264037f/include/boost/pool/pool.hpp#L363

**Posible solution:**
Using some mechanism to avoid the preprocessor convert max function to a preprocessor target.

**Comment by svart-riddare** [comment]
You may also `#define NOMINMAX` before including `Windows.h`, preventing definition `min()` and `max()` macros by system headers.

**Comment by francoisk** [comment]
> You may also `#define NOMINMAX` before including `Windows.h`, preventing definition `min()` and `max()` macros by system headers.

The convention in Boost is apparently to use `BOOST_PREVENT_MACRO_SUBSTITUTION` (which `pool.hpp` already does in multiple places).

**Comment by mclow** [comment]
This should be fixed by https://github.com/boostorg/pool/commit/ec7da07ed13e0c61e50d945b574a12ae7ec83cf4, please test with the 1.85.0 beta candidate (out tomorrow!) and let me know here if it's not fixed.
