### ISSUE TITLE
pool::max_chunks can not pass compile with marco max

### ISSUE THREAD

**Issue by sevencolours24** [boostorg/pool#56]
in boost/pool/pool.hpp line 363, function max_chunks(), call of std::numeric_limits<size_type>::max() will be replaced by marco max defined in minwindef.h on Windows, add () will fix this problem. like (std::numeric_limits<size_type>::max)()

**Comment by mclow** [comment]
Turns out that Boost.Pool already uses both option 2 (wrap in parens) and option 3 (`BOOST_PREVENT_MACRO_SUBSTITUTION`), just not on that call.

Fixed in ec7da07ed13e0c61e50d945b574a12ae7ec83cf4
